version: '3'
services:
  static-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
  dynamic-analysis:
    image: node:20.11.0
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install eslint -g && eslint ."

  test-runner:
    image: node:20.11.0
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm test"
